#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# decomposeReconstruct will be compiled later Allwmake script, when all the
# dependencies are ready

wmakeLnInclude decompositionMethods

wmake libso decompositionMethods
wmake libso metisDecomp
wmake libso parMetisDecomp
wmake libso scotchDecomp


# ----------------------------------------------------------------- end-of-file
